name: ${project.name}
main: ru.easydonate.exploitfix.ExploitFixPlugin
version: ${project.version}
author: SoKnight
load: STARTUP
depend: [ProtocolLib]
description: ${project.description}
api-version: 1.13